### ISSUE TITLE
Erro no comando migrate

### ISSUE THREAD

**Issue by davilos** [Finange/core#18]
Eu segui todos os passos, mas na hora do código `python3 manage.py migrate`, ele deu erro.
Aqui está output:
```
Traceback (most recent call last):
  File "/home/davilos/projects/core/manage.py", line 22, in <module>
    main()
  File "/home/davilos/projects/core/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/davilos/projects/core/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/davilos/projects/core/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/home/davilos/projects/core/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/davilos/projects/core/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/davilos/projects/core/.venv/lib/python3.10/site-packages/django/conf/__init__.py", line 206, in __init__
    raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
ValueError: Incorrect timezone setting: UTC-3
```

**Comment by thehacktour5** [comment]
Fala, Dávilos! Obrigado pela issue! Esse era um erro no "settings" do django. Mas já subi um PR ajustando. 

Você pode da um `git pull` na branch `main` para puxar as atualizações que agora vai funcionar.


Valeu!
